version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MinhaSenhaForte@123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receitas-literarias-app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=ReceitasLiterarias;User=sa;Password=MinhaSenhaForte@123;
      - PORT=5000
    depends_on:
      - db

volumes:
  sqlserver-data:
